# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoviesListTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'ReactiveSwift', '~> 6.1'
pod 'ReactiveCocoa', '~> 10.1'
pod 'Alamofire'
  # Pods for MoviesListTest

end
